# source 'https://rubygems.org'
source 'https://gems.ruby-china.org/'


gem 'sinatra'
gem 'puma'
gem 'mini_magick'
gem 'ruby-opencv', :require => 'opencv'
gem 'algorithms'
gem 'rake'


group :development do
  gem 'rerun'
end

group :test do
  gem 'phashion'
end
